// Static data for GitHub Pages deployment (no backend required)
import type { School, MilitaryBase, AEAMember } from './types';

export const staticSchools: School[] = [
  {
    id: 1,
    name: "Spartan College of Aeronautics",
    type: "Part 147",
    address: "8820 E Pine St",
    city: "Tulsa",
    state: "OK",
    zipCode: "74115",
    latitude: 36.1474,
    longitude: -95.9149,
    email: "admissions@spartan.edu",
    phone: "918-836-6886",
    poc: "John Anderson",
    website: "https://www.spartan.edu"
  },
  {
    id: 2,
    name: "Redstone College",
    type: "Part 147",
    address: "10851 W 120th Ave",
    city: "Broomfield",
    state: "CO",
    zipCode: "80021",
    latitude: 39.9146,
    longitude: -105.0569,
    email: "info@redstone.edu",
    phone: "303-466-1714",
    poc: "Sarah Mitchell",
    website: "https://www.redstone.edu"
  },
  {
    id: 3,
    name: "Pittsburgh Institute of Aeronautics",
    type: "Part 147",
    address: "5 Allegheny County Airport",
    city: "West Mifflin",
    state: "PA",
    zipCode: "15122",
    latitude: 40.3543,
    longitude: -79.9301,
    email: "admissions@pia.edu",
    phone: "412-346-2100",
    poc: "Michael Roberts",
    website: "https://www.pia.edu"
  },
  {
    id: 4,
    name: "St. Philip's College Aviation",
    type: "Technical College",
    address: "10401 IH 10 West",
    city: "San Antonio",
    state: "TX",
    zipCode: "78230",
    latitude: 29.5509,
    longitude: -98.6103,
    email: "aviation@alamo.edu",
    phone: "210-486-2900",
    poc: "Maria Garcia",
    website: "https://www.alamo.edu/spc"
  },
  {
    id: 5,
    name: "Hillsborough Community College",
    type: "Technical College",
    address: "2950 Bellflower Blvd",
    city: "Tampa",
    state: "FL",
    zipCode: "33619",
    latitude: 27.9656,
    longitude: -82.3882,
    email: "aviation@hccfl.edu",
    phone: "813-253-7000",
    poc: "David Williams",
    website: "https://www.hccfl.edu"
  },
  {
    id: 6,
    name: "Purdue University Aviation",
    type: "4-Year Program",
    address: "610 Purdue Mall",
    city: "West Lafayette",
    state: "IN",
    zipCode: "47907",
    latitude: 40.4237,
    longitude: -86.9212,
    email: "aviation@purdue.edu",
    phone: "765-494-5782",
    poc: "Jennifer Thompson",
    website: "https://www.purdue.edu/aviation"
  },
  {
    id: 7,
    name: "Embry-Riddle Aeronautical University",
    type: "4-Year Program",
    address: "600 S Clyde Morris Blvd",
    city: "Daytona Beach",
    state: "FL",
    zipCode: "32114",
    latitude: 29.1878,
    longitude: -81.0479,
    email: "admissions@erau.edu",
    phone: "386-226-6100",
    poc: "Robert Martinez",
    website: "https://www.erau.edu"
  },
  {
    id: 8,
    name: "Arizona State University - Polytechnic",
    type: "4-Year Program",
    address: "6073 S Backus Mall",
    city: "Mesa",
    state: "AZ",
    zipCode: "85212",
    latitude: 33.3058,
    longitude: -111.6803,
    email: "aviation@asu.edu",
    phone: "480-727-1585",
    poc: "Lisa Chen",
    website: "https://poly.engineering.asu.edu"
  },
  {
    id: 9,
    name: "Middle Tennessee State University",
    type: "4-Year Program",
    address: "1301 E Main St",
    city: "Murfreesboro",
    state: "TN",
    zipCode: "37132",
    latitude: 35.8492,
    longitude: -86.3688,
    email: "aerospace@mtsu.edu",
    phone: "615-898-2788",
    poc: "Christopher Lee",
    website: "https://www.mtsu.edu/aerospace"
  },
  {
    id: 10,
    name: "Vaughn College",
    type: "Part 147",
    address: "86-01 23rd Ave",
    city: "Flushing",
    state: "NY",
    zipCode: "11369",
    latitude: 40.7726,
    longitude: -73.8747,
    email: "admissions@vaughn.edu",
    phone: "718-429-6600",
    poc: "Anthony Brown",
    website: "https://www.vaughn.edu"
  },
  {
    id: 11,
    name: "Emily Griffith Technical College",
    type: "Technical College",
    address: "1070 Alton Way",
    city: "Denver",
    state: "CO",
    zipCode: "80230",
    latitude: 39.7298,
    longitude: -104.9378,
    email: "aviation@emilygriffith.edu",
    phone: "720-423-4700",
    poc: "Patricia Davis",
    website: "https://www.emilygriffith.edu"
  },
  {
    id: 12,
    name: "Akron Schools Aviation Program",
    type: "High School",
    address: "4350 Kent Rd",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    latitude: 41.1609,
    longitude: -81.4415,
    email: "aviation@stow.k12.oh.us",
    phone: "330-689-5445",
    poc: "James Wilson",
    website: "https://www.stow.k12.oh.us"
  },
  {
    id: 13,
    name: "Aviation High School",
    type: "High School",
    address: "45-30 36th St",
    city: "Long Island City",
    state: "NY",
    zipCode: "11101",
    latitude: 40.7484,
    longitude: -73.9361,
    email: "info@aviationhs.net",
    phone: "718-786-0110",
    poc: "Nancy Taylor",
    website: "https://www.aviationhs.net"
  },
  {
    id: 14,
    name: "WK Kellogg Airport High School",
    type: "High School",
    address: "6351 S Zephyr Pl",
    city: "Battle Creek",
    state: "MI",
    zipCode: "49037",
    latitude: 42.3081,
    longitude: -85.2505,
    email: "aviation@bcps.k12.mi.us",
    phone: "269-965-9500",
    poc: "Thomas Moore",
    website: "https://www.bcps.k12.mi.us"
  },
  {
    id: 15,
    name: "Colorado Aeronautical Academy",
    type: "High School",
    address: "6161 Business Center Dr",
    city: "Highlands Ranch",
    state: "CO",
    zipCode: "80130",
    latitude: 39.5498,
    longitude: -104.9729,
    email: "info@coloradoaero.org",
    phone: "303-708-1855",
    poc: "Sandra Jackson",
    website: "https://www.coloradoaero.org"
  }
];

export const staticMilitaryBases: MilitaryBase[] = [
  {
    id: 1,
    name: "Tinker Air Force Base",
    branch: "Air Force",
    address: "7437 Arnold St",
    city: "Oklahoma City",
    state: "OK",
    zipCode: "73145",
    latitude: 35.4147,
    longitude: -97.3866,
    email: "tinker.info@us.af.mil",
    phone: "405-739-2011",
    poc: "Col. Sarah Mitchell",
    website: "https://www.tinker.af.mil",
    readinessCenterUrl: "https://www.tinker.af.mil/Resources/Family-Readiness",
    hasAvionicsTechs: true
  },
  {
    id: 2,
    name: "Naval Air Station Pensacola",
    branch: "Navy",
    address: "190 Radford Blvd",
    city: "Pensacola",
    state: "FL",
    zipCode: "32508",
    latitude: 30.3532,
    longitude: -87.2917,
    email: "naspcola.pao@navy.mil",
    phone: "850-452-0111",
    poc: "Capt. James Wilson",
    website: "https://www.cnic.navy.mil/pensacola",
    readinessCenterUrl: "https://www.cnic.navy.mil/pensacola/ffr",
    hasAvionicsTechs: true
  },
  {
    id: 3,
    name: "Joint Base San Antonio",
    branch: "Air Force",
    address: "1701 Kenly Ave",
    city: "San Antonio",
    state: "TX",
    zipCode: "78234",
    latitude: 29.3839,
    longitude: -98.6117,
    email: "jbsa.info@us.af.mil",
    phone: "210-671-1110",
    poc: "Col. Michael Rodriguez",
    website: "https://www.jbsa.mil",
    readinessCenterUrl: "https://www.jbsa.mil/Resources/Family-Programs",
    hasAvionicsTechs: true
  },
  {
    id: 4,
    name: "Naval Air Station Oceana",
    branch: "Navy",
    address: "1878 Tomcat Blvd",
    city: "Virginia Beach",
    state: "VA",
    zipCode: "23460",
    latitude: 36.8206,
    longitude: -76.0325,
    email: "oceana.pao@navy.mil",
    phone: "757-433-2366",
    poc: "Capt. Robert Davis",
    website: "https://www.cnic.navy.mil/oceana",
    readinessCenterUrl: "https://www.cnic.navy.mil/oceana/ffr",
    hasAvionicsTechs: true
  },
  {
    id: 5,
    name: "Hill Air Force Base",
    branch: "Air Force",
    address: "7274 Wardleigh Rd",
    city: "Hill AFB",
    state: "UT",
    zipCode: "84056",
    latitude: 41.1167,
    longitude: -111.9783,
    email: "hill.info@us.af.mil",
    phone: "801-777-7221",
    poc: "Col. Jennifer Thompson",
    website: "https://www.hill.af.mil",
    readinessCenterUrl: "https://www.hill.af.mil/Resources/Airman-Family-Readiness",
    hasAvionicsTechs: true
  },
  {
    id: 6,
    name: "Marine Corps Air Station Miramar",
    branch: "Marines",
    address: "535 Miramar Way",
    city: "San Diego",
    state: "CA",
    zipCode: "92145",
    latitude: 32.8668,
    longitude: -117.1405,
    email: "miramar.pao@usmc.mil",
    phone: "858-577-1011",
    poc: "Col. David Anderson",
    website: "https://www.miramar.marines.mil",
    readinessCenterUrl: "https://www.miramar.marines.mil/Resources/MCCS",
    hasAvionicsTechs: true
  },
  {
    id: 7,
    name: "Nellis Air Force Base",
    branch: "Air Force",
    address: "4430 Grissom Ave",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89191",
    latitude: 36.2361,
    longitude: -115.0345,
    email: "nellis.info@us.af.mil",
    phone: "702-652-1110",
    poc: "Col. Patricia Garcia",
    website: "https://www.nellis.af.mil",
    readinessCenterUrl: "https://www.nellis.af.mil/Resources/Airman-Family",
    hasAvionicsTechs: true
  },
  {
    id: 8,
    name: "Naval Air Station Jacksonville",
    branch: "Navy",
    address: "542 Chambers Ave",
    city: "Jacksonville",
    state: "FL",
    zipCode: "32212",
    latitude: 30.2357,
    longitude: -81.6806,
    email: "nasjax.pao@navy.mil",
    phone: "904-542-2345",
    poc: "Capt. William Chen",
    website: "https://www.cnic.navy.mil/jacksonville",
    readinessCenterUrl: "https://www.cnic.navy.mil/jacksonville/ffr",
    hasAvionicsTechs: true
  },
  {
    id: 9,
    name: "Luke Air Force Base",
    branch: "Air Force",
    address: "14185 Falcon St",
    city: "Glendale",
    state: "AZ",
    zipCode: "85309",
    latitude: 33.5355,
    longitude: -112.3830,
    email: "luke.info@us.af.mil",
    phone: "623-856-6011",
    poc: "Col. Amanda Foster",
    website: "https://www.luke.af.mil",
    readinessCenterUrl: "https://www.luke.af.mil/Resources/Airman-Family",
    hasAvionicsTechs: true
  },
  {
    id: 10,
    name: "Marine Corps Air Station Cherry Point",
    branch: "Marines",
    address: "464 Roberts Rd",
    city: "Havelock",
    state: "NC",
    zipCode: "28532",
    latitude: 34.9008,
    longitude: -76.8808,
    email: "cherrypoint.pao@usmc.mil",
    phone: "252-466-2811",
    poc: "Col. Mark Stevens",
    website: "https://www.cherrypoint.marines.mil",
    readinessCenterUrl: "https://www.cherrypoint.marines.mil/Resources",
    hasAvionicsTechs: true
  }
];

export const staticAEAMembers: AEAMember[] = [
  {
    id: 1,
    name: "Duncan Aviation",
    shopType: "MRO",
    address: "3701 Aviation Rd",
    city: "Lincoln",
    state: "NE",
    zipCode: "68524",
    latitude: 40.8507,
    longitude: -96.7593,
    email: "info@duncanaviation.com",
    phone: "402-475-2611",
    poc: "Robert Duncan",
    website: "https://www.duncanaviation.com",
    certifications: "CRS DKSR172D"
  },
  {
    id: 2,
    name: "StandardAero",
    shopType: "MRO",
    address: "8802 E 34th St N",
    city: "Wichita",
    state: "KS",
    zipCode: "67226",
    latitude: 37.7049,
    longitude: -97.2508,
    email: "info@standardaero.com",
    phone: "316-440-2600",
    poc: "Sarah Johnson",
    website: "https://www.standardaero.com",
    certifications: "CRS STAS245K"
  },
  {
    id: 3,
    name: "Aviation Specialties Unlimited",
    shopType: "Repair Station",
    address: "4632 W Aeronca St",
    city: "Boise",
    state: "ID",
    zipCode: "83705",
    latitude: 43.5667,
    longitude: -116.2227,
    email: "sales@asu.aero",
    phone: "208-389-9658",
    poc: "Mike Anderson",
    website: "https://www.asu.aero",
    certifications: "CRS ASUR561L"
  },
  {
    id: 4,
    name: "AAR Corp",
    shopType: "MRO",
    address: "1100 N Wood Dale Rd",
    city: "Wood Dale",
    state: "IL",
    zipCode: "60191",
    latitude: 41.9642,
    longitude: -87.9836,
    email: "contact@aarcorp.com",
    phone: "630-227-2000",
    poc: "Jennifer Smith",
    website: "https://www.aarcorp.com",
    certifications: "CRS AARR982C"
  },
  {
    id: 5,
    name: "Textron Aviation",
    shopType: "OEM",
    address: "9709 E Central Ave",
    city: "Wichita",
    state: "KS",
    zipCode: "67206",
    latitude: 37.6871,
    longitude: -97.2267,
    email: "support@txtav.com",
    phone: "316-517-6000",
    poc: "David Martinez",
    website: "https://www.txtav.com",
    certifications: "CRS TXTV123A"
  },
  {
    id: 6,
    name: "Flying Colors Corp",
    shopType: "Repair Station",
    address: "N4798 County Rd C",
    city: "Benton",
    state: "WI",
    zipCode: "53803",
    latitude: 42.5714,
    longitude: -90.3414,
    email: "info@flyingcolors.aero",
    phone: "608-759-3601",
    poc: "Lisa Thompson",
    website: "https://www.flyingcolors.aero",
    certifications: "CRS FLCR443B"
  },
  {
    id: 7,
    name: "Jet Aviation",
    shopType: "MRO",
    address: "101 Jet Aviation Dr",
    city: "Teterboro",
    state: "NJ",
    zipCode: "07608",
    latitude: 40.8500,
    longitude: -74.0600,
    email: "teterboro@jetaviation.com",
    phone: "201-288-3700",
    poc: "Michael Chen",
    website: "https://www.jetaviation.com",
    certifications: "CRS JTAV789D"
  },
  {
    id: 8,
    name: "West Star Aviation",
    shopType: "MRO",
    address: "2575 CR 59",
    city: "Grand Junction",
    state: "CO",
    zipCode: "81505",
    latitude: 39.1239,
    longitude: -108.5267,
    email: "info@weststaraviation.com",
    phone: "970-243-7600",
    poc: "Amanda Foster",
    website: "https://www.weststaraviation.com",
    certifications: "CRS WSTR334E"
  },
  {
    id: 9,
    name: "Gulfstream Aerospace",
    shopType: "OEM",
    address: "500 Gulfstream Rd",
    city: "Savannah",
    state: "GA",
    zipCode: "31407",
    latitude: 32.1279,
    longitude: -81.2024,
    email: "customerservice@gulfstream.com",
    phone: "912-965-3000",
    poc: "Mark Williams",
    website: "https://www.gulfstream.com",
    certifications: "CRS GLFM567F"
  },
  {
    id: 10,
    name: "Signature Aviation",
    shopType: "MRO",
    address: "5455 Airport Blvd",
    city: "Orlando",
    state: "FL",
    zipCode: "32812",
    latitude: 28.4339,
    longitude: -81.3084,
    email: "orlando@signatureaviation.com",
    phone: "407-855-0451",
    poc: "Patricia Lee",
    website: "https://www.signatureaviation.com",
    certifications: "CRS SIGN891G"
  },
  {
    id: 11,
    name: "Embraer Services",
    shopType: "OEM",
    address: "277 Martim Francisco Ave",
    city: "Fort Lauderdale",
    state: "FL",
    zipCode: "33315",
    latitude: 26.0994,
    longitude: -80.1502,
    email: "services@embraer.com",
    phone: "954-359-3700",
    poc: "Robert Garcia",
    website: "https://www.embraer.com",
    certifications: "CRS EMBR223H"
  },
  {
    id: 12,
    name: "Stevens Aerospace",
    shopType: "MRO",
    address: "1 Stevens Dr",
    city: "Greenville",
    state: "SC",
    zipCode: "29607",
    latitude: 34.8452,
    longitude: -82.3500,
    email: "info@stevensaerospace.com",
    phone: "864-877-8700",
    poc: "Emily Rodriguez",
    website: "https://www.stevensaerospace.com",
    certifications: "CRS STEV445I"
  },
  {
    id: 13,
    name: "Constant Aviation",
    shopType: "MRO",
    address: "4141 Agar Dr",
    city: "Richmond",
    state: "VA",
    zipCode: "23222",
    latitude: 37.5790,
    longitude: -77.4400,
    email: "info@constantaviation.com",
    phone: "804-222-5200",
    poc: "James Parker",
    website: "https://www.constantaviation.com",
    certifications: "CRS CNST667J"
  },
  {
    id: 14,
    name: "Premier Jet Center",
    shopType: "Repair Station",
    address: "14201 SW 139th Ct",
    city: "Miami",
    state: "FL",
    zipCode: "33186",
    latitude: 25.6866,
    longitude: -80.4115,
    email: "service@premierjet.com",
    phone: "305-233-4359",
    poc: "Michelle Davis",
    website: "https://www.premierjet.com",
    certifications: "CRS PRMJ778K"
  },
  {
    id: 15,
    name: "Pacific Coast Avionics",
    shopType: "Repair Station",
    address: "3550 John Glenn Dr",
    city: "Livermore",
    state: "CA",
    zipCode: "94550",
    latitude: 37.6896,
    longitude: -121.7903,
    email: "sales@pcavionics.com",
    phone: "925-443-3600",
    poc: "Daniel Wilson",
    website: "https://www.pcavionics.com",
    certifications: "CRS PCAV889L"
  }
];
